### ISSUE TITLE
Reload with typescript change is slow?

### ISSUE THREAD

**Issue by asadsahi** [johnpapa/angular2-tour-of-heroes#45]
While project is running using "npm start" and we change a typescript file. It reloads after 5-6 seconds. If we change html file application reloads instantly. 

Note: Looking at the console, typescript watcher kicks in after 5-6 seconds.

Has anyone else experienced this issue?

Thanks

**Comment by johnpapa** [comment]
ive noticed a subtle delay too. about 3 second here for me.

anyone else?

i welcome any contributions to this (its lite-server and typescript doing the work here)

**Comment by stefk** [comment]
See https://github.com/Microsoft/TypeScript/issues/6178. The fix is on its way, but you can downgrade typescript to 1.7.3 in the meanwhile.

**Comment by asadsahi** [comment]
downgraded to 1.7.3, can't see any difference.

**Comment by asadsahi** [comment]
Downgrading to 1.6 works perfect though.

**Comment by johnpapa** [comment]
I think its best if you update the TypeScript issue with this too

**Comment by asadsahi** [comment]
Thanks John, just updated typescript issue #6178.

**Comment by jesusreal** [comment]
I just tried with typescript 1.8.0 and is working very fast now. I think this issue can be closed. In addition, wouldn´t it be a good idea to update the typescript version in package.json content at https://angular.io/docs/ts/latest/quickstart.html so that nobody else has this problem?

**Comment by johnpapa** [comment]
resolved in TS 1.8

use `npm install typescript@next` for now

**Comment by ghost** [comment]
If anybody is still having this issue, make sure that you use the latest version of node and the problem might just go away.

**Comment by georgiosd** [comment]
Not specific to this example but a hello-world type of ng2 app takes about 5sec to compile on my machine both with tsc and gulp-typescript. Any ideas?
